In [ ]:
# Numpy
# np array
# ndim - numero de dimensiones
# shape - numero de columnas
# dtype - data type y numero de bits

In [6]:
import numpy as np

In [18]:
np.__version__

'1.20.1'

In [10]:
array = np.array ([[0,1,2],[2,3,4]])
array

array([[0, 1, 2],
       [2, 3, 4]])

In [13]:
array2 = np.ones ((2,3))
array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
lista = [1,2,3,4,5]
a1 = np.array (lista)
a1

array([1, 2, 3, 4, 5])

In [14]:
a1.ndim

1

In [15]:
a1.shape

(5,)

In [16]:
a1.dtype

dtype('int32')

In [17]:
a1.astype ('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [19]:
2**64

18446744073709551616

In [20]:
2**32

4294967296

In [21]:
lista2 = [[1,2,3,],[4,5,6]]

In [23]:
a2 = np.array (lista2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a2.ndim

2

In [25]:
a2.shape

(2, 3)

In [26]:
a2.dtype

dtype('int32')

In [27]:
np.zeros ((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones ((3,6),'int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [31]:
np.random.randint(1,100,(10,))

array([ 1, 57, 96, 91, 86, 98, 11, 39, 89, 57])

In [ ]:
#Indexing

In [33]:
a3 = np.random.randint(1,100,(3,4))
a3

array([[85, 80,  7, 94],
       [68, 99, 15, 68],
       [46, 63, 55, 79]])

In [35]:
#el 15: fila 1 columna 2, siempre empieza por 0
a3[1,2]

15

In [36]:
#solo la fila 2
a3[2,:]

array([46, 63, 55, 79])

In [37]:
#solo la columna 3
a3[:,3]

array([94, 68, 79])

In [38]:
#solo los 2 primeros de la 1a y 2a fila
a3 [:2,:2]

array([[85, 80],
       [68, 99]])

In [39]:
a3 [:2,2:4]

array([[ 7, 94],
       [15, 68]])

In [41]:
a3 [:2,2:4]

array([[ 7, 94],
       [15, 68]])

In [42]:
a3.shape

(3, 4)

In [ ]:
2 * a3[]

In [40]:
# transposed
a3.T

array([[85, 68, 46],
       [80, 99, 63],
       [ 7, 15, 55],
       [94, 68, 79]])

In [43]:
a3[:,0].reshape(3,1) + a3

array([[170, 165,  92, 179],
       [136, 167,  83, 136],
       [ 92, 109, 101, 125]])

In [44]:
np.vstack([a3,a3])

array([[85, 80,  7, 94],
       [68, 99, 15, 68],
       [46, 63, 55, 79],
       [85, 80,  7, 94],
       [68, 99, 15, 68],
       [46, 63, 55, 79]])

In [45]:
np.vstack([a3,2*a3])

array([[ 85,  80,   7,  94],
       [ 68,  99,  15,  68],
       [ 46,  63,  55,  79],
       [170, 160,  14, 188],
       [136, 198,  30, 136],
       [ 92, 126, 110, 158]])

In [46]:
np.hstack([a3,2*a3])

array([[ 85,  80,   7,  94, 170, 160,  14, 188],
       [ 68,  99,  15,  68, 136, 198,  30, 136],
       [ 46,  63,  55,  79,  92, 126, 110, 158]])

In [48]:
np.hstack([a3,a3,a3])

array([[85, 80,  7, 94, 85, 80,  7, 94, 85, 80,  7, 94],
       [68, 99, 15, 68, 68, 99, 15, 68, 68, 99, 15, 68],
       [46, 63, 55, 79, 46, 63, 55, 79, 46, 63, 55, 79]])

In [47]:
np.repeat (a3,3)

array([85, 85, 85, 80, 80, 80,  7,  7,  7, 94, 94, 94, 68, 68, 68, 99, 99,
       99, 15, 15, 15, 68, 68, 68, 46, 46, 46, 63, 63, 63, 55, 55, 55, 79,
       79, 79])

In [49]:
np.full((3,3),18)

array([[18, 18, 18],
       [18, 18, 18],
       [18, 18, 18]])

In [50]:
np.full(a3.shape,18)

array([[18, 18, 18, 18],
       [18, 18, 18, 18],
       [18, 18, 18, 18]])

In [51]:
np.full_like(a3,18)

array([[18, 18, 18, 18],
       [18, 18, 18, 18],
       [18, 18, 18, 18]])

In [ ]:
#Ficheros (completamente numerico)

In [52]:
a4 = np.genfromtxt (r"C:\\Users\\Natalia Gonzalez\\Ironhack\\notebooks\\data\\numpy_data.txt")
a4

array([nan, nan, nan])

In [71]:
a4 = np.genfromtxt ("../notebooks/data/numpy_data.txt", delimiter=',')
a4

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [69]:
a4 = np.genfromtxt (r"..\\notebooks\\data\\numpy_data.txt", delimiter=',')
a4

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [58]:
#Stats

In [59]:
a3

array([[85, 80,  7, 94],
       [68, 99, 15, 68],
       [46, 63, 55, 79]])

In [60]:
np.sum(a3)

759

In [61]:
np.max(a3)

99

In [62]:
np.min(a3)

7

In [63]:
# suma de los elementos por filas
np.sum(a3, axis=0)

array([199, 242,  77, 241])

In [64]:
# suma de los elementos por columnas
np.sum(a3, axis=1)

array([266, 250, 243])

In [65]:
# media de los elementos por filas
np.mean(a3, axis=0)

array([66.33333333, 80.66666667, 25.66666667, 80.33333333])

In [66]:
np.std(a3, axis=0)

array([15.96524002, 14.70449667, 20.99735433, 10.65624491])